//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam_Gallery
{
    using System;
    using System.Collections.Generic;
    
    public partial class PICTURE_GRADES
    {
        public int Id { get; set; }
        public int Id_User { get; set; }
        public int Id_Picture { get; set; }
        public int Id_Grade { get; set; }
    
        public virtual GRADES GRADES { get; set; }
        public virtual PICTURE PICTURE { get; set; }
        public virtual USER USER { get; set; }
    }
}
